# Generated by Django 6.0 on 2026-01-30 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RetornoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retorno', models.DateField(null=True)),
                ('horario_retorno', models.TimeField(null=True)),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retorno', to='formulario.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_passageiro', models.CharField(max_length=100)),
                ('idade_passageiro', models.IntegerField()),
                ('rg_passageiro', models.CharField(max_length=20)),
                ('orgao_emissor_passageiro', models.CharField(max_length=50)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros', to='formulario.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='ParadasViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_parada', models.CharField(max_length=10)),
                ('rua_parada', models.CharField(max_length=200)),
                ('numero_rua_parada', models.CharField(max_length=10)),
                ('complemento_parada', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade_parada', models.CharField(max_length=100)),
                ('uf_parada', models.CharField(max_length=50)),
                ('bairro_parada', models.CharField(max_length=50)),
                ('horario_parada', models.TimeField()),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='formulario.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='OrigemViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_origem', models.CharField(max_length=10)),
                ('rua_origem', models.CharField(max_length=200)),
                ('numero_rua_origem', models.CharField(max_length=10)),
                ('complemento_origem', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade_origem', models.CharField(max_length=100)),
                ('estado_origem', models.CharField(max_length=50)),
                ('bairro_origem', models.CharField(max_length=50)),
                ('data_saida', models.DateField()),
                ('horario_saida', models.TimeField()),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='formulario.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='DestinoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_destino', models.CharField(max_length=10)),
                ('rua_destino', models.CharField(max_length=200)),
                ('numero_rua_destino', models.CharField(max_length=10)),
                ('complemento_destino', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade_destino', models.CharField(max_length=100)),
                ('estado_destino', models.CharField(max_length=50)),
                ('bairro_destino', models.CharField(max_length=50)),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='formulario.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='DadosAeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_voo', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_chegada_voo', models.TimeField(blank=True, null=True)),
                ('quantidade_malas', models.IntegerField(blank=True, null=True)),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_aeroporto', to='formulario.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='Contratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivacao_viagem', models.CharField(max_length=200)),
                ('nome_contratante', models.CharField(max_length=100)),
                ('rg_contratante', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone_contratante', models.CharField(max_length=20)),
                ('orgao_emissor_contratante', models.CharField(max_length=50)),
                ('cpf_cnpj_contratante', models.CharField(max_length=20)),
                ('cep_contratante', models.CharField(max_length=10)),
                ('rua_contratante', models.CharField(max_length=100)),
                ('numero_rua_contratante', models.CharField(max_length=10)),
                ('complemento_contratante', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro_contratante', models.CharField(max_length=100)),
                ('cidade_contratante', models.CharField(max_length=100)),
                ('estado_contratante', models.CharField(max_length=50)),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratante', to='formulario.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_adicional', to='formulario.viagem')),
            ],
        ),
    ]
