# Generated by Django 6.0 on 2026-01-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retornoviagem',
            name='data_retorno',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='retornoviagem',
            name='horario_retorno',
            field=models.TimeField(null=True),
        ),
    ]
