# Generated by Django 6.0 on 2026-02-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratante',
            name='cep_contratante',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='destinoviagem',
            name='cep_destino',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='origemviagem',
            name='cep_origem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paradasviagem',
            name='cep_parada',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
