# Generated by Django 6.0 on 2026-01-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_retornoviagem_data_retorno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_voo', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_chegada_voo', models.TimeField(blank=True, null=True)),
                ('quantidade_malas', models.IntegerField(blank=True, null=True)),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_aeroporto', to='formulario.viagem')),
            ],
        ),
    ]
