# Generated by Django 6.0 on 2026-01-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_dadosaeroporto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_adicional', to='formulario.viagem')),
            ],
        ),
    ]
