# Generated by Django 6.0 on 2026-01-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_comentarioadicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradasviagem',
            name='complemento_parada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
